project:
  type: website
  resources:
    - ads.txt   

website:
  title: "André Mancha"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Sobre
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Matemática Financeira
        href: https://andre-mancha.github.io/MatFin/

  page-footer:
    center: "© André Mancha"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



